version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: markdown-it
    versions:
    - 12.0.5
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.22.0
    - 7.24.0
  - dependency-name: vue
    versions:
    - 3.0.10
    - 3.0.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.2.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 2.0.0-rc.0
    - 2.0.0-rc.1
    - 2.0.0-rc.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.1
    - 7.0.2
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: markdown-it-ins
    versions:
    - 3.0.1
  - dependency-name: markdown-it-mark
    versions:
    - 3.0.1
